version: '3'
services:
  api:
    build: ./api
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 3002:3002
  client:
    build: ./client
    ports:
      - 3000:3000
  ooth:
    build: ./ooth
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 3001:3001
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/db/data
    volumes:
      - ./db/data:/db/data
    ports:
      - 27017:27017
    command: mongod